version: '3.8'
services:
  testing-system:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.testing_system
    image: testing-system:dev
    ports:
      - ${TESTING_SYSTEM_PORT:-8881}:${TESTING_SYSTEM_PORT:-8881}
    volumes:
      - ./config:/testing_system/config
      - ./experiments:/testing_system/experiments
      - ./experiment_results:/testing_system/experiment_results
      - ./prompts:/testing_system/prompts
    environment:
      - TESTING_CONFIG_PATH=/testing_system/config/config.yaml
      - EXPERIMENTS_PATH=/testing_system/experiments
      - RESULTS_PATH=/testing_system/experiment_results
      - PROMPTS_PATH=/testing_system/prompts
      - DEEPEVAL_CACHE_DIR=/tmp/.deepeval
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HF_TOKEN=${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - chat-network
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${TESTING_SYSTEM_PORT:-8881}/health"]
      interval: 10s
      timeout: 5s
      retries: 1
      
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - ${OLLAMA_PORT:-11434}:${OLLAMA_PORT:-11434}
    volumes:
      - /.ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - chat-network
    restart: unless-stopped
    profiles: ["ollama"]

  etl-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.etl
    container_name: chat-prep-etl-service
    ports:
      - ${ETL_PORT:-8067}:${ETL_PORT:-8067}
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./sessions:/app/sessions
      - ./zipdata:/app/zipdata 
    environment:
      - ETL_CONFIG_PATH=/app/config/config.yaml
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY=bee
      - QDRANT_COLLECTION_NAME=messages
      - TG_API_ID=34395921
      - TG_API_HASH=a86566d239b6d15c97b57d48637b27be
      - TG_PROXY_ADDR=host.docker.internal
      - TG_PROXY_PORT=10808
      - TG_PROXY_TYPE=socks5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - qdrant
    networks:
      - chat-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-vector-db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
      - ./zipdata:/app/data
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge


volumes:
  ollama_data: