[workspace]
name = "chat-prep-etl"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64"]

# --- 1. General ---
[dependencies]
python-dotenv = "*"
pyyaml = "*"
requests = "*"
pandas = "*"

# --- 2. ETL ---
[feature.etl.dependencies]
python = "3.11.*"
bs4 = "*"
lxml = "*"
emoji = "*"
pymorphy2 = "*"
python-socks = ">=2.8.1,<3"


[feature.etl.pypi-dependencies]
natasha = ">=1.6.0, <2"
pymorphy2-dicts-ru = "*"
telethon = "*"
setuptools = "==69.5.1" 
qdrant-client = ">=1.18.0, <2"
fastembed = ">=0.8.0, <0.9"
fastapi = ">=0.136.1, <0.137"
uvicorn = ">=0.46.0, <0.47"






# --- 3.  FRONT  ---
[feature.front.dependencies]
python = "3.12.*"
fastapi = "*"
uvicorn = "*"

[feature.front.pypi-dependencies]
python-multipart = "*"




# --- 4. LLM ---
[feature.llm.dependencies]
python = "3.12.*"
fastapi = "*"
uvicorn = "*"
qdrant-client = "*"
fastembed = "*"

# ------
[environments]
etl-env = ["etl"]
front-env = ["front"]
llm-env = ["llm"]

[pypi-dependencies]
qdrant-client = ">=1.18.0, <2"
