testing_system:
  host: "0.0.0.0"
  port: 8501
  num_process_workers: 1
  num_eval_workers: 1

  eval:
    metrics: ["latency","token_count","bert_score","jaccard_distance","rouge_l_f1","hallucination_rate","numeric_accuracy","overlap"]
    bert_model: "bert-base-multilingual-cased"
    hallucination_model: "cointegrated/rubert-base-cased-nli-threeway"

  assistants:
    type: ollama 
    ollama:
      host: "ollama"
      port: 11434
      model: "gemma:2b"    # only one model per ollama is available
    cloud:
      base_url: "https://ai.api.cloud.yandex.net/v1"
      model: "gpt://b1gt8b2ef4mq1ufc4dil/gpt-oss-20b/latest"
      temperature: 0.3

  retrievers:
    type: etl_service
    etl_service:
      chat_id: 0
      k: 15
      host: 100.76.31.66
      port: 8067

  registries:
    type: local
    local:
      path: ${EXPERIMENTS_PATH:/experiment_results}

  loaders:
    type: yaml
    path: ${EXPERIMENTS_PATH:/experiments}

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: default
      stream: ext://sys.stderr                # явно указываем stderr
  root:
    level: DEBUG
    handlers: [console]