# ЭТАП 1: Сборка окружения через Pixi
FROM ghcr.io/prefix-dev/pixi:latest AS build

WORKDIR /app
COPY pixi.toml pixi.loc[k] ./
COPY conda_pypi_mapping.json ./

# Устанавливаем зависимости строго для etl-env
RUN pixi install --environment etl-env

RUN find /app/.pixi/envs/etl-env \
      -type d \( -name "__pycache__" -o -name "tests" -o -name "test" \) \
      -exec rm -rf {} + 2>/dev/null || true && \
    find /app/.pixi/envs/etl-env \
      -name "*.pyc" -o -name "*.pyo" \
      -delete 2>/dev/null || true

# Генерируем скрипт активации окружения СТРОГО в /app/shell-hook.sh
RUN pixi shell-hook --environment etl-env > /app/shell-hook.sh
RUN echo 'exec "$@"' >> /app/shell-hook.sh


# ЭТАП 2: Легковесный финальный образ для запуска
#FROM nvidia/cuda:12.1.1-base-ubuntu22.04
FROM ubuntu:22.04

# Устанавливаем только самый минимум для работы системных скриптов
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    bash \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Переносим готовое окружение и скрипт активации из папки /app первого этапа
COPY --from=build /app/.pixi/envs/etl-env /app/.pixi/envs/etl-env
COPY --from=build /app/shell-hook.sh /app/shell-hook.sh

# Делаем скрипт исполняемым на всякий случай
RUN chmod +x /app/shell-hook.sh

# Копируем исходный код приложения
COPY src/etl/ /app/src/etl/

# Создаем нужные папки для сессий и логов (включая test_servise из прошлой ошибки)
RUN mkdir -p logs sessions temp_extracted test_servise

EXPOSE 8067

# Точка входа: теперь путь железно указывает на /app/shell-hook.sh
ENTRYPOINT ["/bin/bash", "/app/shell-hook.sh"]
CMD ["python", "-m", "src.etl.adapter.repository_test"]